import NavbarComponent from '@/components/Navbar'
import './globals.css'
import { Providers } from './providers'

export const metadata = {
  title: 'E-commerce Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body>
        <NavbarComponent />
        <main>
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  )
}
